# Generated by Django 3.2.6 on 2021-08-07 01:20

from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.png', upload_to=stores.models.get_product_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(upload_to=stores.models.get_product_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(upload_to=stores.models.get_product_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(upload_to=stores.models.get_product_name),
        ),
    ]
