# Generated by Django 3.2.6 on 2021-08-07 14:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210806_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to=accounts.models.user_profile_images),
        ),
    ]
