# Generated by Django 3.2.6 on 2021-08-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210806_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
