# Generated by Django 3.2.6 on 2021-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_product_stocks_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stocks_left',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
